import {
  BarChart3,
  BookOpen,
  CalendarCheck2,
  FileUp,
  LayoutDashboard,
  Bell,
  Settings,
  UserCog,
  UserCircle2,
  Users,
  ClipboardList,
  Wrench,
  Building2,
} from "lucide-react";

export const sidebarItemsByRole = {
  admin: [
    { key: "dashboard", label: "Dashboard", icon: LayoutDashboard, to: "/admin-dashboard", end: true },
    { key: "users", label: "User Management", icon: UserCog, to: "/admin-dashboard/users" },
    { key: "resources", label: "Resources", icon: Building2, to: "/admin-dashboard/resources" },
    { key: "bookings", label: "Bookings", icon: CalendarCheck2, to: "/admin-dashboard/bookings" },
    { key: "incidents", label: "Incidents", icon: Wrench, to: "/admin-dashboard/incidents" },
    { key: "notifications", label: "Notifications", icon: Bell, to: "/admin-dashboard/notifications" },
    { key: "reports", label: "Reports", icon: BarChart3, to: "/admin-dashboard/reports" },
    { key: "profile", label: "Profile", icon: UserCircle2, to: "/admin-dashboard/profile" },
    { key: "settings", label: "Settings", icon: Settings, to: "/admin-dashboard/settings" },
  ],
  lecturer: [
    { key: "dashboard", label: "Dashboard", icon: LayoutDashboard, to: "/lecturer-dashboard", end: true },
    { key: "bookings", label: "Bookings", icon: CalendarCheck2, to: "/lecturer-dashboard/bookings" },
    { key: "resources", label: "Resources", icon: Building2, to: "/lecturer-dashboard/resources" },
    { key: "incidents", label: "Incidents", icon: Wrench, to: "/lecturer-dashboard/incidents" },
    { key: "notifications", label: "Notifications", icon: Bell, to: "/lecturer-dashboard/notifications" },
    { key: "profile", label: "Profile", icon: UserCircle2, to: "/lecturer-dashboard/profile" },
    { key: "settings", label: "Settings", icon: Settings, to: "/lecturer-dashboard/settings" },
  ],
  student: [
    { key: "dashboard", label: "Dashboard", icon: LayoutDashboard, to: "/student-dashboard", end: true },
    { key: "courses", label: "My Courses", icon: BookOpen, to: "/student-dashboard/courses" },
    { key: "materials", label: "Materials", icon: FileUp, to: "/student-dashboard/materials" },
    { key: "bookings", label: "Book Resources", icon: CalendarCheck2, to: "/student-dashboard/bookings" },
    { key: "assignments", label: "Assignments", icon: ClipboardList, to: "/student-dashboard/assignments" },
    { key: "notifications", label: "Notifications", icon: Bell, to: "/student-dashboard/notifications" },
    { key: "profile", label: "Profile", icon: UserCircle2, to: "/student-dashboard/profile" },
    { key: "settings", label: "Settings", icon: Settings, to: "/student-dashboard/settings" },
  ],
  technician: [
    { key: "dashboard", label: "Dashboard", icon: LayoutDashboard, to: "/technician-dashboard", end: true },
    { key: "tickets", label: "Incidents", icon: Wrench, to: "/technician-dashboard/tickets" },
    { key: "tasks", label: "Tasks", icon: ClipboardList, to: "/technician-dashboard/tasks" },
    { key: "notifications", label: "Notifications", icon: Bell, to: "/technician-dashboard/notifications" },
    { key: "profile", label: "Profile", icon: UserCircle2, to: "/technician-dashboard/profile" },
    { key: "settings", label: "Settings", icon: Settings, to: "/technician-dashboard/settings" },
  ],
};
